# Noah Badner, 2021
#
# Even Fibonacci numbers
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
# first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
# even-valued terms.


def main():
    """Main method"""
    fib_sum = 0
    term_1, term_2 = 1, 2
    while term_2 <= 4000000:
        if term_2 % 2 == 0:
            fib_sum += term_2
        term_1, term_2 = term_2, term_1 + term_2
    print(fib_sum)


if __name__ == "__main__":
    main()
